//-----------------------------Debut nettoyage des donnees PTBA Raccrochage----------------------------------------
UPDATE ptba_raccrochage SET CODE_MINISTERE=REPLACE(CODE_MINISTERE,"'",""),CODE_PROGRAMME=REPLACE(CODE_PROGRAMME,"'",""),CODE_ACTION=REPLACE(CODE_ACTION,"'",""),CODE_NOMENCLATURE_BUDGETAIRE=REPLACE(CODE_NOMENCLATURE_BUDGETAIRE,"'",""),ARTICLE_ECONOMIQUE=REPLACE(ARTICLE_ECONOMIQUE,"'",""),NATURE_ECONOMIQUE=REPLACE(NATURE_ECONOMIQUE,"'",""),DIVISION_FONCTIONNELLE=REPLACE(DIVISION_FONCTIONNELLE,"'",""),GROUPE_FONCTIONNELLE=REPLACE(GROUPE_FONCTIONNELLE,"'",""),CLASSE_FONCTIONNELLE=REPLACE(CLASSE_FONCTIONNELLE,"'",""),CODES_PROGRAMMATIQUE=REPLACE(CODES_PROGRAMMATIQUE,"'","") WHERE 1

UPDATE
ptba_raccrochage
SET
INTITULE_MINISTERE=TRIM(INTITULE_MINISTERE),
INTITULE_PROGRAMME=TRIM(INTITULE_PROGRAMME),
OBJECTIF_PROGRAMME=TRIM(OBJECTIF_PROGRAMME),
LIBELLE_ACTION=TRIM(LIBELLE_ACTION),
OBJECTIF_ACTION=TRIM(OBJECTIF_ACTION),
INTITULE_ARTICLE_ECONOMIQUE=TRIM(INTITULE_ARTICLE_ECONOMIQUE),
INTITULE_NATURE_ECONOMIQUE=TRIM(INTITULE_NATURE_ECONOMIQUE),
INTITULE_DIVISION_FONCTIONNELLE=TRIM(INTITULE_DIVISION_FONCTIONNELLE),
INTITULE_GROUPE_FONCTIONNELLE=TRIM(INTITULE_GROUPE_FONCTIONNELLE),
INTITULE_CLASSE_FONCTIONNELLE=TRIM(INTITULE_CLASSE_FONCTIONNELLE),
ACTIVITES=TRIM(ACTIVITES),
RESULTATS_ATTENDUS=TRIM(RESULTATS_ATTENDUS),
UNITE=TRIM(UNITE),
RESPONSABLE=TRIM(RESPONSABLE),
INTITULE_DES_GRANDES_MASSES=TRIM(INTITULE_DES_GRANDES_MASSES);

UPDATE
ptba_raccrochage
SET
INTITULE_MINISTERE=REPLACE(INTITULE_MINISTERE,"\n"," "),
INTITULE_PROGRAMME=REPLACE(INTITULE_PROGRAMME,"\n"," "),
OBJECTIF_PROGRAMME=REPLACE(OBJECTIF_PROGRAMME,"\n"," "),
LIBELLE_ACTION=REPLACE(LIBELLE_ACTION,"\n"," "),
OBJECTIF_ACTION=REPLACE(OBJECTIF_ACTION,"\n"," "),
INTITULE_ARTICLE_ECONOMIQUE=REPLACE(INTITULE_ARTICLE_ECONOMIQUE,"\n"," "),
INTITULE_NATURE_ECONOMIQUE=REPLACE(INTITULE_NATURE_ECONOMIQUE,"\n"," "),
INTITULE_DIVISION_FONCTIONNELLE=REPLACE(INTITULE_DIVISION_FONCTIONNELLE,"\n"," "),
INTITULE_GROUPE_FONCTIONNELLE=REPLACE(INTITULE_GROUPE_FONCTIONNELLE,"\n"," "),
INTITULE_CLASSE_FONCTIONNELLE=REPLACE(INTITULE_CLASSE_FONCTIONNELLE,"\n"," "),
ACTIVITES=REPLACE(ACTIVITES,"\n"," "),
RESULTATS_ATTENDUS=REPLACE(RESULTATS_ATTENDUS,"\n"," "),
UNITE=REPLACE(UNITE,"\n"," "),
RESPONSABLE=REPLACE(RESPONSABLE,"\n"," "),
INTITULE_DES_GRANDES_MASSES=REPLACE(INTITULE_DES_GRANDES_MASSES,"\n"," ");

UPDATE
ptba_raccrochage
SET
INTITULE_MINISTERE=REPLACE(INTITULE_MINISTERE,"  "," "),
INTITULE_PROGRAMME=REPLACE(INTITULE_PROGRAMME,"  "," "),
OBJECTIF_PROGRAMME=REPLACE(OBJECTIF_PROGRAMME,"  "," "),
LIBELLE_ACTION=REPLACE(LIBELLE_ACTION,"  "," "),
OBJECTIF_ACTION=REPLACE(OBJECTIF_ACTION,"  "," "),
INTITULE_ARTICLE_ECONOMIQUE=REPLACE(INTITULE_ARTICLE_ECONOMIQUE,"  "," "),
INTITULE_NATURE_ECONOMIQUE=REPLACE(INTITULE_NATURE_ECONOMIQUE,"  "," "),
INTITULE_DIVISION_FONCTIONNELLE=REPLACE(INTITULE_DIVISION_FONCTIONNELLE,"  "," "),
INTITULE_GROUPE_FONCTIONNELLE=REPLACE(INTITULE_GROUPE_FONCTIONNELLE,"  "," "),
INTITULE_CLASSE_FONCTIONNELLE=REPLACE(INTITULE_CLASSE_FONCTIONNELLE,"  "," "),
ACTIVITES=REPLACE(ACTIVITES,"  "," "),
RESULTATS_ATTENDUS=REPLACE(RESULTATS_ATTENDUS,"  "," "),
UNITE=REPLACE(UNITE,"  "," "),
RESPONSABLE=REPLACE(RESPONSABLE,"  "," "),
INTITULE_DES_GRANDES_MASSES=REPLACE(INTITULE_DES_GRANDES_MASSES,"  "," ");


SELECT * FROM ptba_raccrochage WHERE (QT1 LIKE '%,%' AND QT1 LIKE '%.%') OR (QT2 LIKE '%,%' AND QT2 LIKE '%.%') OR (QT3 LIKE '%,%' AND QT3 LIKE '%.%') OR (QT4 LIKE '%,%' AND QT4 LIKE '%.%') OR (T1 LIKE '%,%' AND T1 LIKE '%.%') OR (T2 LIKE '%,%' AND T2 LIKE '%.%') OR (T3 LIKE '%,%' AND T3 LIKE '%.%') OR (T4 LIKE '%,%' AND T4 LIKE '%.%') OR (COUT_UNITAIRE_BIF LIKE '%,%' AND COUT_UNITAIRE_BIF LIKE '%.%') OR (QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%,%' AND QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%.%') OR (PROGRAMMATION_FINANCIERE_BIF LIKE '%,%' AND PROGRAMMATION_FINANCIERE_BIF LIKE '%.%')

SELECT * FROM ptba_raccrochage WHERE QT1 LIKE '%,%' OR QT2 LIKE '%,%' OR QT3 LIKE '%,%' OR QT4 LIKE '%,%' OR T1 LIKE '%,%' OR T2 LIKE '%,%' OR T3 LIKE '%,%' OR T4 LIKE '%,%' OR COUT_UNITAIRE_BIF LIKE '%,%' OR QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%,%' OR PROGRAMMATION_FINANCIERE_BIF LIKE '%,%';

SELECT * FROM ptba_raccrochage WHERE QT1 LIKE '%.%' OR QT2 LIKE '%.%' OR QT3 LIKE '%.%' OR QT4 LIKE '%.%' OR T1 LIKE '%.%' OR T2 LIKE '%.%' OR T3 LIKE '%.%' OR T4 LIKE '%.%' OR COUT_UNITAIRE_BIF LIKE '%.%' OR QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%.%' OR PROGRAMMATION_FINANCIERE_BIF LIKE '%.%'


UPDATE ptba_raccrochage SET QT1=REPLACE(QT1,",","."),QT2=REPLACE(QT2,",","."),QT3=REPLACE(QT3,",","."),QT4=REPLACE(QT4,",","."),COUT_UNITAIRE_BIF=REPLACE(COUT_UNITAIRE_BIF,",","."),T1=REPLACE(T1,",","."),T2=REPLACE(T2,",","."),T3=REPLACE(T3,",","."),T4=REPLACE(T4,",","."),PROGRAMMATION_FINANCIERE_BIF=REPLACE(PROGRAMMATION_FINANCIERE_BIF,",",".") WHERE QT1 LIKE '%,%' OR QT2 LIKE '%,%' OR QT3 LIKE '%,%' OR QT4 LIKE '%,%' OR COUT_UNITAIRE_BIF LIKE '%,%' OR T1 LIKE '%,%' OR T2 LIKE '%,%' OR T3 LIKE '%,%' OR T4 LIKE '%,%' OR PROGRAMMATION_FINANCIERE_BIF LIKE '%,%';

UPDATE ptba_raccrochage SET QT1=REPLACE(QT1," ",""),QT2=REPLACE(QT2," ",""),QT3=REPLACE(QT3," ",""),QT4=REPLACE(QT4," ",""),COUT_UNITAIRE_BIF=REPLACE(COUT_UNITAIRE_BIF," ",""),T1=REPLACE(T1," ",""),T2=REPLACE(T2," ",""),T3=REPLACE(T3," ",""),T4=REPLACE(T4," ",""),PROGRAMMATION_FINANCIERE_BIF=REPLACE(PROGRAMMATION_FINANCIERE_BIF," ","") WHERE 1

UPDATE ptba_raccrochage SET ACTIVITES=REPLACE(ACTIVITES,"'"," ");
//-----------------------------Fin nettoyage des donnees PTBA Raccrochage----------------------------------------


//-----------------------------Debut nettoyage des donnees PTBA Ancien----------------------------------------
UPDATE ptba_bdd13 SET CODE_MINISTERE=REPLACE(CODE_MINISTERE,"'",""),CODE_PROGRAMME=REPLACE(CODE_PROGRAMME,"'",""),CODE_ACTION=REPLACE(CODE_ACTION,"'",""),CODE_NOMENCLATURE_BUDGETAIRE=REPLACE(CODE_NOMENCLATURE_BUDGETAIRE,"'",""),ARTICLE_ECONOMIQUE=REPLACE(ARTICLE_ECONOMIQUE,"'",""),NATURE_ECONOMIQUE=REPLACE(NATURE_ECONOMIQUE,"'",""),DIVISION_FONCTIONNELLE=REPLACE(DIVISION_FONCTIONNELLE,"'",""),GROUPE_FONCTIONNELLE=REPLACE(GROUPE_FONCTIONNELLE,"'",""),CLASSE_FONCTIONNELLE=REPLACE(CLASSE_FONCTIONNELLE,"'",""),CODES_PROGRAMMATIQUE=REPLACE(CODES_PROGRAMMATIQUE,"'","") WHERE 1

UPDATE
ptba_bdd13
SET
INTITULE_MINISTERE=TRIM(INTITULE_MINISTERE),
INTITULE_PROGRAMME=TRIM(INTITULE_PROGRAMME),
OBJECTIF_PROGRAMME=TRIM(OBJECTIF_PROGRAMME),
LIBELLE_ACTION=TRIM(LIBELLE_ACTION),
OBJECTIF_ACTION=TRIM(OBJECTIF_ACTION),
INTITULE_ARTICLE_ECONOMIQUE=TRIM(INTITULE_ARTICLE_ECONOMIQUE),
INTITULE_NATURE_ECONOMIQUE=TRIM(INTITULE_NATURE_ECONOMIQUE),
INTITULE_DIVISION_FONCTIONNELLE=TRIM(INTITULE_DIVISION_FONCTIONNELLE),
INTITULE_GROUPE_FONCTIONNELLE=TRIM(INTITULE_GROUPE_FONCTIONNELLE),
INTITULE_CLASSE_FONCTIONNELLE=TRIM(INTITULE_CLASSE_FONCTIONNELLE),
ACTIVITES=TRIM(ACTIVITES),
RESULTATS_ATTENDUS=TRIM(RESULTATS_ATTENDUS),
UNITE=TRIM(UNITE),
RESPONSABLE=TRIM(RESPONSABLE),
INTITULE_DES_GRANDES_MASSES=TRIM(INTITULE_DES_GRANDES_MASSES);

UPDATE
ptba_bdd13
SET
INTITULE_MINISTERE=REPLACE(INTITULE_MINISTERE,"\n"," "),
INTITULE_PROGRAMME=REPLACE(INTITULE_PROGRAMME,"\n"," "),
OBJECTIF_PROGRAMME=REPLACE(OBJECTIF_PROGRAMME,"\n"," "),
LIBELLE_ACTION=REPLACE(LIBELLE_ACTION,"\n"," "),
OBJECTIF_ACTION=REPLACE(OBJECTIF_ACTION,"\n"," "),
INTITULE_ARTICLE_ECONOMIQUE=REPLACE(INTITULE_ARTICLE_ECONOMIQUE,"\n"," "),
INTITULE_NATURE_ECONOMIQUE=REPLACE(INTITULE_NATURE_ECONOMIQUE,"\n"," "),
INTITULE_DIVISION_FONCTIONNELLE=REPLACE(INTITULE_DIVISION_FONCTIONNELLE,"\n"," "),
INTITULE_GROUPE_FONCTIONNELLE=REPLACE(INTITULE_GROUPE_FONCTIONNELLE,"\n"," "),
INTITULE_CLASSE_FONCTIONNELLE=REPLACE(INTITULE_CLASSE_FONCTIONNELLE,"\n"," "),
ACTIVITES=REPLACE(ACTIVITES,"\n"," "),
RESULTATS_ATTENDUS=REPLACE(RESULTATS_ATTENDUS,"\n"," "),
UNITE=REPLACE(UNITE,"\n"," "),
RESPONSABLE=REPLACE(RESPONSABLE,"\n"," "),
INTITULE_DES_GRANDES_MASSES=REPLACE(INTITULE_DES_GRANDES_MASSES,"\n"," ");

UPDATE
ptba_bdd13
SET
INTITULE_MINISTERE=REPLACE(INTITULE_MINISTERE,"  "," "),
INTITULE_PROGRAMME=REPLACE(INTITULE_PROGRAMME,"  "," "),
OBJECTIF_PROGRAMME=REPLACE(OBJECTIF_PROGRAMME,"  "," "),
LIBELLE_ACTION=REPLACE(LIBELLE_ACTION,"  "," "),
OBJECTIF_ACTION=REPLACE(OBJECTIF_ACTION,"  "," "),
INTITULE_ARTICLE_ECONOMIQUE=REPLACE(INTITULE_ARTICLE_ECONOMIQUE,"  "," "),
INTITULE_NATURE_ECONOMIQUE=REPLACE(INTITULE_NATURE_ECONOMIQUE,"  "," "),
INTITULE_DIVISION_FONCTIONNELLE=REPLACE(INTITULE_DIVISION_FONCTIONNELLE,"  "," "),
INTITULE_GROUPE_FONCTIONNELLE=REPLACE(INTITULE_GROUPE_FONCTIONNELLE,"  "," "),
INTITULE_CLASSE_FONCTIONNELLE=REPLACE(INTITULE_CLASSE_FONCTIONNELLE,"  "," "),
ACTIVITES=REPLACE(ACTIVITES,"  "," "),
RESULTATS_ATTENDUS=REPLACE(RESULTATS_ATTENDUS,"  "," "),
UNITE=REPLACE(UNITE,"  "," "),
RESPONSABLE=REPLACE(RESPONSABLE,"  "," "),
INTITULE_DES_GRANDES_MASSES=REPLACE(INTITULE_DES_GRANDES_MASSES,"  "," ");


SELECT * FROM ptba_bdd13 WHERE (QT1 LIKE '%,%' AND QT1 LIKE '%.%') OR (QT2 LIKE '%,%' AND QT2 LIKE '%.%') OR (QT3 LIKE '%,%' AND QT3 LIKE '%.%') OR (QT4 LIKE '%,%' AND QT4 LIKE '%.%') OR (T1 LIKE '%,%' AND T1 LIKE '%.%') OR (T2 LIKE '%,%' AND T2 LIKE '%.%') OR (T3 LIKE '%,%' AND T3 LIKE '%.%') OR (T4 LIKE '%,%' AND T4 LIKE '%.%') OR (COUT_UNITAIRE_BIF LIKE '%,%' AND COUT_UNITAIRE_BIF LIKE '%.%') OR (QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%,%' AND QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%.%') OR (PROGRAMMATION_FINANCIERE_BIF LIKE '%,%' AND PROGRAMMATION_FINANCIERE_BIF LIKE '%.%')

SELECT * FROM ptba_bdd13 WHERE QT1 LIKE '%,%' OR QT2 LIKE '%,%' OR QT3 LIKE '%,%' OR QT4 LIKE '%,%' OR T1 LIKE '%,%' OR T2 LIKE '%,%' OR T3 LIKE '%,%' OR T4 LIKE '%,%' OR COUT_UNITAIRE_BIF LIKE '%,%' OR QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%,%' OR PROGRAMMATION_FINANCIERE_BIF LIKE '%,%';

SELECT * FROM ptba_bdd13 WHERE QT1 LIKE '%.%' OR QT2 LIKE '%.%' OR QT3 LIKE '%.%' OR QT4 LIKE '%.%' OR T1 LIKE '%.%' OR T2 LIKE '%.%' OR T3 LIKE '%.%' OR T4 LIKE '%.%' OR COUT_UNITAIRE_BIF LIKE '%.%' OR QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%.%' OR PROGRAMMATION_FINANCIERE_BIF LIKE '%.%'


UPDATE ptba_bdd13 SET QT1=REPLACE(QT1,",","."),QT2=REPLACE(QT2,",","."),QT3=REPLACE(QT3,",","."),QT4=REPLACE(QT4,",","."),COUT_UNITAIRE_BIF=REPLACE(COUT_UNITAIRE_BIF,",","."),T1=REPLACE(T1,",","."),T2=REPLACE(T2,",","."),T3=REPLACE(T3,",","."),T4=REPLACE(T4,",","."),PROGRAMMATION_FINANCIERE_BIF=REPLACE(PROGRAMMATION_FINANCIERE_BIF,",",".") WHERE QT1 LIKE '%,%' OR QT2 LIKE '%,%' OR QT3 LIKE '%,%' OR QT4 LIKE '%,%' OR COUT_UNITAIRE_BIF LIKE '%,%' OR T1 LIKE '%,%' OR T2 LIKE '%,%' OR T3 LIKE '%,%' OR T4 LIKE '%,%' OR PROGRAMMATION_FINANCIERE_BIF LIKE '%,%';

UPDATE ptba_bdd13 SET QT1=REPLACE(QT1," ",""),QT2=REPLACE(QT2," ",""),QT3=REPLACE(QT3," ",""),QT4=REPLACE(QT4," ",""),COUT_UNITAIRE_BIF=REPLACE(COUT_UNITAIRE_BIF," ",""),T1=REPLACE(T1," ",""),T2=REPLACE(T2," ",""),T3=REPLACE(T3," ",""),T4=REPLACE(T4," ",""),PROGRAMMATION_FINANCIERE_BIF=REPLACE(PROGRAMMATION_FINANCIERE_BIF," ","") WHERE 1

UPDATE ptba_bdd13 SET ACTIVITES=REPLACE(ACTIVITES,"'"," ");
//-----------------------------Fin nettoyage des donnees PTBA Ancien----------------------------------------



//-----------------------------Debut nettoyage des donnees PTBA revise----------------------------------------
UPDATE ptba_revise SET CODE_MINISTERE=REPLACE(CODE_MINISTERE,"'",""),CODE_PROGRAMME=REPLACE(CODE_PROGRAMME,"'",""),CODE_ACTION=REPLACE(CODE_ACTION,"'",""),CODE_NOMENCLATURE_BUDGETAIRE=REPLACE(CODE_NOMENCLATURE_BUDGETAIRE,"'",""),ARTICLE_ECONOMIQUE=REPLACE(ARTICLE_ECONOMIQUE,"'",""),NATURE_ECONOMIQUE=REPLACE(NATURE_ECONOMIQUE,"'",""),DIVISION_FONCTIONNELLE=REPLACE(DIVISION_FONCTIONNELLE,"'",""),GROUPE_FONCTIONNELLE=REPLACE(GROUPE_FONCTIONNELLE,"'",""),CLASSE_FONCTIONNELLE=REPLACE(CLASSE_FONCTIONNELLE,"'",""),CODES_PROGRAMMATIQUE=REPLACE(CODES_PROGRAMMATIQUE,"'","") WHERE 1

UPDATE
ptba_revise
SET
INTITULE_MINISTERE=TRIM(INTITULE_MINISTERE),
INTITULE_PROGRAMME=TRIM(INTITULE_PROGRAMME),
OBJECTIF_PROGRAMME=TRIM(OBJECTIF_PROGRAMME),
LIBELLE_ACTION=TRIM(LIBELLE_ACTION),
OBJECTIF_ACTION=TRIM(OBJECTIF_ACTION),
INTITULE_ARTICLE_ECONOMIQUE=TRIM(INTITULE_ARTICLE_ECONOMIQUE),
INTITULE_NATURE_ECONOMIQUE=TRIM(INTITULE_NATURE_ECONOMIQUE),
INTITULE_DIVISION_FONCTIONNELLE=TRIM(INTITULE_DIVISION_FONCTIONNELLE),
INTITULE_GROUPE_FONCTIONNELLE=TRIM(INTITULE_GROUPE_FONCTIONNELLE),
INTITULE_CLASSE_FONCTIONNELLE=TRIM(INTITULE_CLASSE_FONCTIONNELLE),
ACTIVITES=TRIM(ACTIVITES),
RESULTATS_ATTENDUS=TRIM(RESULTATS_ATTENDUS),
UNITE=TRIM(UNITE),
RESPONSABLE=TRIM(RESPONSABLE),
INTITULE_DES_GRANDES_MASSES=TRIM(INTITULE_DES_GRANDES_MASSES);

UPDATE
ptba_revise
SET
INTITULE_MINISTERE=REPLACE(INTITULE_MINISTERE,"\n"," "),
INTITULE_PROGRAMME=REPLACE(INTITULE_PROGRAMME,"\n"," "),
OBJECTIF_PROGRAMME=REPLACE(OBJECTIF_PROGRAMME,"\n"," "),
LIBELLE_ACTION=REPLACE(LIBELLE_ACTION,"\n"," "),
OBJECTIF_ACTION=REPLACE(OBJECTIF_ACTION,"\n"," "),
INTITULE_ARTICLE_ECONOMIQUE=REPLACE(INTITULE_ARTICLE_ECONOMIQUE,"\n"," "),
INTITULE_NATURE_ECONOMIQUE=REPLACE(INTITULE_NATURE_ECONOMIQUE,"\n"," "),
INTITULE_DIVISION_FONCTIONNELLE=REPLACE(INTITULE_DIVISION_FONCTIONNELLE,"\n"," "),
INTITULE_GROUPE_FONCTIONNELLE=REPLACE(INTITULE_GROUPE_FONCTIONNELLE,"\n"," "),
INTITULE_CLASSE_FONCTIONNELLE=REPLACE(INTITULE_CLASSE_FONCTIONNELLE,"\n"," "),
ACTIVITES=REPLACE(ACTIVITES,"\n"," "),
RESULTATS_ATTENDUS=REPLACE(RESULTATS_ATTENDUS,"\n"," "),
UNITE=REPLACE(UNITE,"\n"," "),
RESPONSABLE=REPLACE(RESPONSABLE,"\n"," "),
INTITULE_DES_GRANDES_MASSES=REPLACE(INTITULE_DES_GRANDES_MASSES,"\n"," ");


UPDATE
ptba_revise
SET
INTITULE_MINISTERE=REPLACE(INTITULE_MINISTERE,"  "," "),
INTITULE_PROGRAMME=REPLACE(INTITULE_PROGRAMME,"  "," "),
OBJECTIF_PROGRAMME=REPLACE(OBJECTIF_PROGRAMME,"  "," "),
LIBELLE_ACTION=REPLACE(LIBELLE_ACTION,"  "," "),
OBJECTIF_ACTION=REPLACE(OBJECTIF_ACTION,"  "," "),
INTITULE_ARTICLE_ECONOMIQUE=REPLACE(INTITULE_ARTICLE_ECONOMIQUE,"  "," "),
INTITULE_NATURE_ECONOMIQUE=REPLACE(INTITULE_NATURE_ECONOMIQUE,"  "," "),
INTITULE_DIVISION_FONCTIONNELLE=REPLACE(INTITULE_DIVISION_FONCTIONNELLE,"  "," "),
INTITULE_GROUPE_FONCTIONNELLE=REPLACE(INTITULE_GROUPE_FONCTIONNELLE,"  "," "),
INTITULE_CLASSE_FONCTIONNELLE=REPLACE(INTITULE_CLASSE_FONCTIONNELLE,"  "," "),
ACTIVITES=REPLACE(ACTIVITES,"  "," "),
RESULTATS_ATTENDUS=REPLACE(RESULTATS_ATTENDUS,"  "," "),
UNITE=REPLACE(UNITE,"  "," "),
RESPONSABLE=REPLACE(RESPONSABLE,"  "," "),
INTITULE_DES_GRANDES_MASSES=REPLACE(INTITULE_DES_GRANDES_MASSES,"  "," ");


SELECT * FROM ptba_revise WHERE (QT1 LIKE '%,%' AND QT1 LIKE '%.%') OR (QT2 LIKE '%,%' AND QT2 LIKE '%.%') OR (QT3 LIKE '%,%' AND QT3 LIKE '%.%') OR (QT4 LIKE '%,%' AND QT4 LIKE '%.%') OR (T1 LIKE '%,%' AND T1 LIKE '%.%') OR (T2 LIKE '%,%' AND T2 LIKE '%.%') OR (T3 LIKE '%,%' AND T3 LIKE '%.%') OR (T4 LIKE '%,%' AND T4 LIKE '%.%') OR (COUT_UNITAIRE_BIF LIKE '%,%' AND COUT_UNITAIRE_BIF LIKE '%.%') OR (QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%,%' AND QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%.%') OR (PROGRAMMATION_FINANCIERE_BIF LIKE '%,%' AND PROGRAMMATION_FINANCIERE_BIF LIKE '%.%')

SELECT * FROM ptba_revise WHERE QT1 LIKE '%,%' OR QT2 LIKE '%,%' OR QT3 LIKE '%,%' OR QT4 LIKE '%,%' OR T1 LIKE '%,%' OR T2 LIKE '%,%' OR T3 LIKE '%,%' OR T4 LIKE '%,%' OR COUT_UNITAIRE_BIF LIKE '%,%' OR QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%,%' OR PROGRAMMATION_FINANCIERE_BIF LIKE '%,%';

SELECT * FROM ptba_revise WHERE QT1 LIKE '%.%' OR QT2 LIKE '%.%' OR QT3 LIKE '%.%' OR QT4 LIKE '%.%' OR T1 LIKE '%.%' OR T2 LIKE '%.%' OR T3 LIKE '%.%' OR T4 LIKE '%.%' OR COUT_UNITAIRE_BIF LIKE '%.%' OR QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE LIKE '%.%' OR PROGRAMMATION_FINANCIERE_BIF LIKE '%.%'


UPDATE ptba_revise SET QT1=REPLACE(QT1,",","."),QT2=REPLACE(QT2,",","."),QT3=REPLACE(QT3,",","."),QT4=REPLACE(QT4,",","."),COUT_UNITAIRE_BIF=REPLACE(COUT_UNITAIRE_BIF,",","."),T1=REPLACE(T1,",","."),T2=REPLACE(T2,",","."),T3=REPLACE(T3,",","."),T4=REPLACE(T4,",","."),PROGRAMMATION_FINANCIERE_BIF=REPLACE(PROGRAMMATION_FINANCIERE_BIF,",","."),QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE=REPLACE(QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE,",",".") WHERE QT1 LIKE '%,%' OR QT2 LIKE '%,%' OR QT3 LIKE '%,%' OR QT4 LIKE '%,%' OR COUT_UNITAIRE_BIF LIKE '%,%' OR T1 LIKE '%,%' OR T2 LIKE '%,%' OR T3 LIKE '%,%' OR T4 LIKE '%,%' OR PROGRAMMATION_FINANCIERE_BIF LIKE '%,%';


UPDATE ptba_revise SET QT1=REPLACE(QT1," ",""),QT2=REPLACE(QT2," ",""),QT3=REPLACE(QT3," ",""),QT4=REPLACE(QT4," ",""),COUT_UNITAIRE_BIF=REPLACE(COUT_UNITAIRE_BIF," ",""),T1=REPLACE(T1," ",""),T2=REPLACE(T2," ",""),T3=REPLACE(T3," ",""),T4=REPLACE(T4," ",""),PROGRAMMATION_FINANCIERE_BIF=REPLACE(PROGRAMMATION_FINANCIERE_BIF," ",""),QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE=REPLACE(QUANTITE_TOTALE_PROGRAMMATION_PHYSIQUE," ","") WHERE 1

UPDATE ptba_revise SET ACTIVITES=REPLACE(ACTIVITES,"'"," ");
//-----------------------------Debut nettoyage des donnees PTBA revise----------------------------------------